name: Docker Image CI

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    IMAGE: external
    HUB_ID: ${{ secrets.DOCKER_HUB_ID }}

jobs:

  run_node_tests:
    name: run npm test scripts
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node context
        uses: actions/setup-node@v3

      - name: install dependencies
        run: npm i

      - name: run node tests
        run: npm test


  build:
    name: build docker image
    needs: [run_node_tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
